### ISSUE TITLE
Using FlatBuffers

### ISSUE THREAD

**Issue by abitrolly** [sourcegraph/scip#115]
https://google.github.io/flatbuffers/ looks like more simple Procol Buffers alternative. Does it worth to use it instead?

**Comment by varungandhi-src** [comment]
Our existing indexers already use Protobuf in some form or the other, so introducing yet another format needs to have substantial benefit to justify the cost of migration: https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/.*%24+file:.*%5C.proto%24&patternType=standard&sm=1&groupBy=repo

The main touted benefits of FlatBuffers are:
- (De-)Serialization performance: This is good enough with Protobuf. For deserialization, yes you can technically operate on the data directly, but the Sourcegraph backend bits ingesting the data would need non-trivial refactoring (and would likely become less ergonomic to work with) for questionable gain.
- Code size: This has not been a problem with Protobuf.
