### ISSUE TITLE
Proposal: create a relationship for method return type

### ISSUE THREAD

**Issue by maks-ivanov** [sourcegraph/scip#155]
Right now, I don't see a sensible way to connect a method return type to method definition, this seems like a Relationship that could be added, like "Returns" or "IsReturnedBy"
This would be useful for features that display Call Hierarchy

**Comment by olafurpg** [comment]
Thank you for reporting! I agree that there should be a way to discover a method's return type. I am unsure if a symbol relationship is the way to go, or another solution like adding `SymbolInformation.signature` that can encode all details of the return type (type parameters, unions, literal types, etc.). 

> This would be useful for features that display Call Hierarchy

Can you elaborate on how you would use the return type for call hierarchies?

**Comment by maks-ivanov** [comment]
I think I was low on sleep when I wrote this, it's not actually that relevant to call hierarchy, but still a useful feature nonetheless!
A structured signature field would work here, I've been working with scip-python and using the documentation field to parse out the relevant signature bits from raw string

**Comment by smheidrich** [comment]
In what form would a return type specifically show up in `signature_documentation`, assuming a "perfect" indexer?

I get that it should probably be an `Occurrence` under `signature_documentation.occurences` (and perhaps also a `SymbolInformation` under `signature_documentation.symbols` if the type is only defined "in-line" in the signature and nowhere else, although I think few languages support that), but neither the `SymbolRole` enum used for `Occurrence.symbol_role` nor the `SyntaxKind` enum for `Occurrence.syntax_kind` seem to have any values to indicate "return type" 🤔 

I tried to figure this out experimentally using scip-rust, scip-python, and scip-typescript, but the first only writes to `signature_documentation.text` and the latter two don't seem to produce `signature_documentation` at all 🤷 

Perhaps I overestimate the degree to which SCIP is meant to represented details like that in a structured way 🤔
