### ISSUE TITLE
Is there a place to discuss with the devs about SCIP?

### ISSUE THREAD

**Issue by sam-ulrich1** [sourcegraph/scip#161]
I'm consuming scip indexes and have some questions about relationships. Sorry to open an issue but I couldn't find a place like Discussions

**Comment by olafurpg** [comment]
Thank you for opening an issue! It's OK to ask a question here.

I just enabled "Discussions" for this repository so you can also post there https://github.com/sourcegraph/scip/discussions/162

We also have a `#scip-dev` channel in the Sourcegraph Discord https://discord.gg/sourcegraph-969688426372825169
