### ISSUE TITLE
Automate generation of Haskell bindings

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip#18]
- [ ] Update `dev/proto-generate.sh` + Buf files as needed.
- [ ] Update asdf action and protobuf workflow: This will catch errors if the Haskell bindings are out-of-sync.
- [ ] Update `Development.md` to mention the Haskell bindings.
- [ ] Remove manual instructions from bindings/haskell/README.md

**Comment by olafurpg** [comment]
Closing as fixed, the Haskell bindings are now automatically generated by `proto-generate.sh`
