### ISSUE TITLE
Please update crates.io with new releases

### ISSUE THREAD

**Issue by gigaroby** [sourcegraph/scip#198]
Hi, the release of the scip crate on crates.io is over a year old and it looks like there have been several new releases since. Would it be possible to cut a new release?

Related #4 #28

**Comment by jdorfman** [comment]
Thanks for the ping @gigaroby. Stay tuned.

**Comment by gigaroby** [comment]
Please also note #202 before updating the release.

**Comment by varungandhi-src** [comment]
I've automated the crate releases and published v0.3.1
