### ISSUE TITLE
question: why SymbolInformation and Relationship outputs are empty

### ISSUE THREAD

**Issue by PorcoRosso85** [sourcegraph/scip#201]
I've written code in this repository:
https://github.com/PorcoRosso85/scip_init. 
The purpose of the code is to check whether dependencies can be successfully retrieved from SCIP. 
In index.ts, I've imported hello.ts and bye.ts and invoked their public functions. I expected either or both of the outputs—SymbolInformation and Relationship—to indicate that index.ts depends on hello.ts and bye.ts.

However, the SymbolInformation and Relationship outputs are empty. These outputs were verified from the index.scip file generated in the root directory of this repository using the SCIP-TypeScript CLI tool. For verification, I implemented log output in binding.ts, located in the same directory, using the TypeScript bindings provided in the SCIP source code.

Below is the output when running the test on binding.ts. I used ViTest for testing, but since it's only executing the log output, there's no dependency on ViTest.

The expected output is the same as stated before: either or both of the outputs should indicate that index.ts is dependent on hello.ts and bye.ts.

Test Output:

```
stdout | src/scip/binding.ts > SCIP > Symbolクラスの出力
scheme does not exist on the object.
package does not exist on the object.
has_package does not exist on the object.
descriptors does not exist on the object.
toObject: {
  scheme: '\x12\x18\n\x0Fscip-typescript\x12\x050.3.9\x1A*file:///home/user/pjs/vite_domain/src/scip \x01',
  package: {
    manager: 'index.ts',
    name: '\n\x03\f\x06\t\x12\x07local 1\x18\x00',
    version: '\n\x07local 7\x1A\x19```ts\nvar expect: any\n```'
  },
  descriptors: []
}

stdout | src/scip/binding.ts > SCIP > SymbolInformationクラスの出力
toObject: {
  symbol: '\x12\x18\n\x0Fscip-typescript\x12\x050.3.9\x1A*file:///home/user/pjs/vite_domain/src/scip \x01',
  documentation: [],
  relationships: []
}

 ✓ src/scip/binding.ts (3)
   ✓ SCIP (3)
     ✓ Indexクラスの出力
     ✓ Symbolクラスの出力
     ✓ SymbolInformationクラスの出力

 Test Files  1 passed (1)
      Tests  3 passed (3)
   Start at  14:44:48
   Duration  1.21s (transform 124ms, setup 0ms, collect 137ms, tests 14ms, environment 0ms, prepare 195ms)

Waiting for the debugger to disconnect...
```

I hope this version is easier to understand. If you have further questions or if there's anything you think I might have misunderstood, please feel free to ask.

**Comment by varungandhi-src** [comment]
Here is some of the output from `scip print index.scip` on your `index.scip` file. So the SymbolInformation output isn't empty. Relationships are only filled when applicable (e.g. a type implementing an interface).

```
	  Symbols: []*scip.SymbolInformation{
        &scip.SymbolInformation{
          Symbol:        "scip-typescript npm . . `bye.ts`/",
          Documentation: []string{
            "```ts\nmodule \"bye.ts\"\n```",
          },
          Relationships:          []*scip.Relationship(nil),
          Kind:                   0,
          DisplayName:            "",
          SignatureDocumentation: (*scip.Document)(nil),
          EnclosingSymbol:        "",
        },
        &scip.SymbolInformation{
          Symbol:        "scip-typescript npm . . `bye.ts`/bye().",
          Documentation: []string{
            "```ts\nfunction bye(name: string): void\n```",
          },
          Relationships:          []*scip.Relationship(nil),
          Kind:                   0,
          DisplayName:            "",
          SignatureDocumentation: (*scip.Document)(nil),
          EnclosingSymbol:        "",
        },
        &scip.SymbolInformation{
          Symbol:        "scip-typescript npm . . `bye.ts`/bye().(name)",
          Documentation: []string{
            "```ts\n(parameter) name: string\n```",
          },
          Relationships:          []*scip.Relationship(nil),
          Kind:                   0,
          DisplayName:            "",
          SignatureDocumentation: (*scip.Document)(nil),
          EnclosingSymbol:        "",
        },
      },
```

> I expected either or both of the outputs—SymbolInformation and Relationship—to indicate that index.ts depends on hello.ts and bye.ts.

File-level dependency information is not directly encoded in SCIP. However, it can be inferred by performing a transitive closure over the graph formed by definitions and references. Specifically, each Occurrence is a node in the graph, and for Occurrences which have the same symbol string, you can add an edge from every Reference occurrence to every Definition occurrence (normally, there should only be 1 Definition Occurrence).

Occurrences would then be grouped by file/Document (as is the case by default) to infer file-level dependency information.

Could you please double-check the `scip print` (or `scip print --json`) output and point out what you think is wrong?

**Comment by PorcoRosso85** [comment]
Thanks.

I'll check it later.
I'm in another project now. Which should I keep this issue close once for returning  again, or open it?
If I can, close this once.

**Comment by varungandhi-src** [comment]
OK, closing this issue for now. We can re-open it if you think the indexer output is incorrect. Generally, for indexer-specific issues, it's better to open the issue on the indexer's repo. If you have a question about SCIP semantics, it is better to open an issue in this repo.
