### ISSUE TITLE
Request to release scip cli

### ISSUE THREAD

**Issue by matthewnitschke-wk** [sourcegraph/scip#229]
https://github.com/sourcegraph/scip/pull/226 contains a new feature that I'd like to use in [scip-dart's](https://github.com/Workiva/scip-dart) CI process

Could the scip-cli be released so this diagnostic information can be included in generated snapshots?

**Comment by varungandhi-src** [comment]
Thanks for the reminder, done. https://github.com/sourcegraph/scip/releases/tag/v0.3.3
