### ISSUE TITLE
Clarification on Extracting Call Relationships in Python Projects Using SCIP-Python

### ISSUE THREAD

**Issue by HarryCollins2** [sourcegraph/scip#263]
Hi there,

I hope this message finds you well.

I am currently working on parsing and extracting the call relationships within a Python project using SCIP-Python. I have a couple of questions regarding this:

	1.	Does the SCIP file contain the call relationships for the functions in the project?
	2.	If so, could you please guide me on how to extract these call relationships and find the call trees for each function?

I appreciate your help and look forward to your response.

Thank you!

**Comment by sansmoraxz** [comment]
I kinda raised a similar question in #259 FYI
