### ISSUE TITLE
Automate publishing of Rust bindings to crates.io

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/scip#28]

**Comment by alvaroclementev** [comment]
Hi! Is there any update on this issue? 

I was looking into using the Rust bindings, and searching on crates.io I can only find this result: https://crates.io/crates/scip which looks like the right one (owned by Sourcegraph) but hasn't been updated in 8 months.

What's the current recommended way for an external project to depend on the bindings? 

Thanks!
