### ISSUE TITLE
CLI improvements: proper argument parsing + subcommands

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip#3]
We should introduce a subcommand structure

```bash
scip lsif --from=dump.lsif-typed --to=dump.lsif
scip lsif --from=dump.lsif --to=dump.lsif-typed
scip snapshot --output-directory=foobar
```

We could probably use the built-in `flag` package.

Let's break this up into two pieces:

- [x] Adding support for the conversion subcommand. (already implemented, with a slightly different structure)
- [x] Adding support for the snapshot subcommand. This is mostly implemented, but it needs to be exposed in a cross-language way. Right now, the implementation has some problems:
  - It assumes that the language has prefix-based line comments, which is not always true (e.g. OCaml doesn't have line comments.)
  - ~It assumes that indentation doesn't matter and creates a difference in indentation between the input and output. However, I think it would be better to avoid that.~ I think this is probably too complicated. Sublime does something similar in its tests, so I guess it is fine that the resulting code is not valid. 🤷 
  - It assumes that the indexer uses tabwidth=1, which seems unusual.

  ~A "tricky" situation to consider here: Haskell commonly has definitions at the start of the line. Maybe we allow a `--comment-syntax=<blah>` argument, or `[--line-comment-syntax=<blah> | --multiline-comment-syntax=<blah>]`. A special string (say `<content>`) in the syntax will be replaced with the snapshot text. For multiline comments (either marked explicitly, or implicitly interpreted form `--comment-syntax`), we can coalesce them for readability. For Haskell's case, snapshots would end up looking like:~
    ```haskell
    addOne :: Int -> Int
    {-
    ^^^^^^ definition addOne
              ^^^ reference Int
                  ^^ reference (->)
                     ^^^ reference Int
    -}
    ```
    (Ignore the above, on thinking about it a bit more, I think it would be way more complicated to implement than it is worth.)

_Originally posted by @olafurpg in https://github.com/sourcegraph/sourcegraph/issues/34983#issuecomment-1118592093_

**Comment by olafurpg** [comment]
Closing as fixed. I don't think we need to worry too much about support comment syntax for OCaml/Haskell yet. It's not a given that the OCaml/Haskell indexers will use the `scip snapshot` command anyways for testing purposes. For example, we'll probably keep the current TS/Java snapshot logic in scip-{java,typescript} because it's easy to tweak for our needs. It's also not a hard requirement that the generated snapshot code is 100% valid syntactically, it's mostly helpful for syntax highlighting.
