### ISSUE TITLE
Is it possible to read the indexed data without Sourcegraph?

### ISSUE THREAD

**Issue by matiaslgh** [sourcegraph/scip#64]
Hi there!

Is there a way to read the indexed data without using Sourcegraph?

I'm working on a project where the server should support LSP communication from indexed data and I was going to use LSIF until I read this post: [SCIP - a better code indexing format than LSIF](https://about.sourcegraph.com/blog/announcing-scip)

The thing is that for LSIF I was going to use a tool like [LSIF reader](https://github.com/ionide/LSIF-Reader) in order to get the data from the dump and then I was going to implement something to handle LSP communication.. but I'm not sure about how to do something like that using SCIP.. 

Is there a tool to do that?
Do I need a tool to do that?
I tried generating a dump of a javascript file using `scip-typescript index --infer-tsconfig` and the result wasn't human-readable

I hope it's ok to ask here, but let me know if not..

thank you :)

**Comment by varungandhi-src** [comment]
Hey Matias! It sounds like there are a couple of options.

1. Read SCIP natively in TypeScript code. You could do this using the generated [TypeScript bindings](https://github.com/sourcegraph/scip/tree/main/bindings/typescript), e.g. by adding a Git-based dependency in your `package.json`.
1. Convert SCIP to LSIF and use LSIF reader: It is possible to convert SCIP data to LSIF using the [scip convert](https://github.com/sourcegraph/scip#scip-convert) command. We don't have binary releases of the SCIP CLI yet, but you should be able to build it like a typical Go project.
    ```bash
    git clone https://github.com/sourcegraph/scip.git --depth=1 && cd scip
    go build -o scip ./cmd
    ./scip --help
    ```

>  I tried generating a dump of a javascript file using scip-typescript index --infer-tsconfig and the result wasn't human-readable

Right, the index is in protobuf, which is a binary format. For debugging purposes, you can inspect the index using:

```
# Generate index.scip using scip-typescript
protoc --decode=scip.Index -I /path/to/cloned/scip scip.proto < ./index.scip
```

The output of this shouldn't be consumed programmatically.

**Comment by matiaslgh** [comment]
Thank you for your response! yes, it resolves my issue. I'm going with option 1 😄

**Comment by varungandhi-src** [comment]
I've created a PR to document this better. https://github.com/sourcegraph/scip/pull/69
