### ISSUE TITLE
Release needed for `x86_64` target or better install script

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/scip#85]
I ran the note in the release

```
TAG="v0.2.0" \
RELEASE_URL="https://github.com/sourcegraph/scip/releases/download/$TAG" \
OS="$(uname -s | tr '[:upper:]' '[:lower:]')" \
curl -L "$RELEASE_URL/scip-$OS-$(uname -m).tar.gz" \
  | tar xzf - scip
```

but on my mac `$(uname -m)` returns `x86_64` and tries to download `scip-darwin-x86_64.tar.gz` which doesn't exist (changing it to `amd64` works).

**Comment by varungandhi-src** [comment]
Thanks for reporting, I've added an extra `sed` to the release note.
