### ISSUE TITLE
Better automation for --version

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip#99]
Idea:
- Use a separate `cli_version.txt` file (or similar).
- Embed the file inside the binary and use that for printing the version.
- Create a small release shell script which adds both the git tag, modifies the version file and does anything else that is necessary. 
- Add a check in the release pipeline that for a release binary, the compiled binary's printed `--version` is the same as the tag. (To avoid an accidental trigger of the release pipeline due to a direct tag push to actually publish a release with the wrong `--version`).

**Comment by abitrolly** [comment]
Have you considered maintaining version info with `ldflags`? https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications

**Comment by varungandhi-src** [comment]
The problem with using `-ldflags` is that it is easy to make a mistake when building (forgetting the pass the flag) and getting a different result. Generally, I'd like to keep `go build` (without any extra flags) working (because that's a more common operation), whereas wrapping any commands for releases is OK because those are not going to be performed as frequently.
